[package]
name = "memory_pool_system"
version = "0.0.2"
authors = ["Sebastian Wicki <gandro@gmx.net>", "Nick Zbinden <niklaus.zbinden@gmail>"]

[workspace]

[dependencies]
mps-sys = { path = "./mps-sys" }
