# .travis.yml -- Travis CI configuration for the MPS
# $Id: //info.ravenbrook.com/project/mps/version/1.114/.travis.yml#1 $
# See <http://about.travis-ci.org/docs/user/languages/c/>.
language: c
compiler:
  - clang
  - gcc
notifications:
  email:
    - mps-travis@ravenbrook.com
  irc: "irc.freenode.net#memorypoolsystem"
script:
  - ./configure --prefix=$PWD/prefix && make install && make test
